### ISSUE TITLE
solved: Unable to deploy Serverless Next.js

### ISSUE THREAD

**Issue by notrab** [moltin/js-sdk#253]
The only error returned from the build is

```bash
module initialization error: Error
    at Object.fs.mkdirSync (fs.js:885:18)
    at LocalStorage.F614.LocalStorage.init (/var/task/page.js:15:15221)
    at new LocalStorage (/var/task/page.js:15:14350)
    at new LocalStorageFactory (/var/task/page.js:44:51796)
    at new Config (/var/task/page.js:44:52717)
    at gateway (/var/task/page.js:44:79222)
    at Object.LUOC (/var/task/page.js:23:64375)
    at webpack\_require (/var/task/page.js:1:339)
    at Module.Hwy/ (/var/task/page.js:23:24875)
    at \_webpack\_require (/var/task/page.js:1:339)
```

Removing the SDK removes that error from the build and Next does its thing as expected, my guess is `fs` is the issue, even with webpack configured.

I've created a project that duplicates this issue: https://github.com/notrab/moltin-sdk-serverless-next-bug

**Comment by johnrjj** [comment]
Had the same issue. Using `memoryStorage` is our workaround:

```
const Moltin = MoltinGateway({
  client_id: process.env.MOLTIN_CLIENT_ID,
  storage: new MemoryStorageFactory(),
});
```
